version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGDATABASE: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: 
          name: Get psql cli
          command: sudo apt-get update && sudo apt-get install -y postgresql-client
      
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mkdir -p /tmp/test-results

      - run: cat db-init.sql | psql $POSTGRES_DB
      
      - run:
          name: Setup pgTAP
          command: |
            sudo apt-get install parallel libgetopt-declare-perl \
            && echo yes | sudo cpan App::cpanminus \
            && echo yes | sudo cpan TAP::Parser::SourceHandler::pgTAP

      - run:
          name: Check pgTAP install
          command: perl -MTAP::Parser::SourceHandler::pgTAP -e 'print;'

      - run:
          name: Run tests
          command: pg_prove test/**/*.sql

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
